# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.img1 = QtWidgets.QLabel(self.centralwidget)
        self.img1.setGeometry(QtCore.QRect(30, 170, 220, 220))
        self.img1.setFrameShape(QtWidgets.QFrame.Box)
        self.img1.setObjectName("img1")
        self.img2 = QtWidgets.QLabel(self.centralwidget)
        self.img2.setGeometry(QtCore.QRect(290, 170, 220, 220))
        self.img2.setFrameShape(QtWidgets.QFrame.Box)
        self.img2.setObjectName("img2")
        self.img3 = QtWidgets.QLabel(self.centralwidget)
        self.img3.setGeometry(QtCore.QRect(550, 170, 220, 220))
        self.img3.setFrameShape(QtWidgets.QFrame.Box)
        self.img3.setObjectName("img3")
        self.Show_img = QtWidgets.QPushButton(self.centralwidget)
        self.Show_img.setGeometry(QtCore.QRect(30, 70, 100, 41))
        self.Show_img.setObjectName("Show_img")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.img1.setText(_translate("MainWindow", "Src_img"))
        self.img2.setText(_translate("MainWindow", "Gray_img"))
        self.img3.setText(_translate("MainWindow", "HSV_img"))
        self.Show_img.setText(_translate("MainWindow", "Show img"))
