# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line_mes = QtWidgets.QLineEdit(self.centralwidget)
        self.line_mes.setGeometry(QtCore.QRect(80, 120, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line_mes.setFont(font)
        self.line_mes.setObjectName("line_mes")
        self.text_mes = QtWidgets.QTextEdit(self.centralwidget)
        self.text_mes.setGeometry(QtCore.QRect(80, 180, 261, 141))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.text_mes.setFont(font)
        self.text_mes.setObjectName("text_mes")
        self.plain_mes = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plain_mes.setGeometry(QtCore.QRect(80, 340, 261, 141))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plain_mes.setFont(font)
        self.plain_mes.setObjectName("plain_mes")
        self.Show = QtWidgets.QPushButton(self.centralwidget)
        self.Show.setGeometry(QtCore.QRect(80, 50, 131, 51))
        self.Show.setObjectName("Show")
        self.text_show = QtWidgets.QTextEdit(self.centralwidget)
        self.text_show.setGeometry(QtCore.QRect(450, 180, 261, 141))
        self.text_show.setObjectName("text_show")
        self.plain_show = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plain_show.setGeometry(QtCore.QRect(450, 340, 261, 141))
        self.plain_show.setObjectName("plain_show")
        self.line_show = QtWidgets.QLineEdit(self.centralwidget)
        self.line_show.setGeometry(QtCore.QRect(450, 120, 261, 41))
        self.line_show.setObjectName("line_show")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.line_mes.setText(_translate("MainWindow", "line_mes"))
        self.text_mes.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:13pt;\">text_mes</span></p></body></html>"))
        self.plain_mes.setPlainText(_translate("MainWindow", "plain_mes"))
        self.Show.setText(_translate("MainWindow", "Show text"))
        self.text_show.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">text_show</p></body></html>"))
        self.plain_show.setPlainText(_translate("MainWindow", "plain_show"))
        self.line_show.setText(_translate("MainWindow", "line_show"))
